### ISSUE TITLE
Nevermind!

### ISSUE THREAD

**Issue by 684efs3** [ztalbot2000/DAWG-UnScramble#1]
Nevermind!

**Comment by ztalbot2000** [comment]
Hi,

  I have not looked at that in years :-). The link to it actually running
is in the README and is still on BeNiceGames.com. The front end javascript
only works for IOS and I never cared to figure out why.

For your question, I will have to go through the code and have a look
again. It's been that long.  I will get back to you probably by sometime
tomorrow.

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hi,

  So the decimal numbers in the javascript correspond to the hex numbers in
the .c file. The C source creates the DAWG which is essentially a table
lookup of possible words based on what letters are available.
 The hard work is done in the C file. The javascript portion is used to do
the word search based on the already created dictionary.
 The meaning of the values make more sense when you look at them in hex, in
which case they are part of the lookup structure.
  I had originally taken this code from scramble-ui, but it did not have
the reverse lookup feature I needed to unscramble all possible words from a
given set of letters.  Current web pages that do this have tons of adds.
 My code allows you to go back and forth, creating a dictionary and also
proving it.  I certainly learned a lot about what a DAWG was at the time.
It was also my first javascript program.
  I hope this helps,

John

**Comment by ztalbot2000** [comment]
Hi,
   I closed this issue, but you may be interested in UnScramble v2 which fixes the web page being properly created on modern web browsers. Previously UnScramble would include the binary dictionary file which goes against ACL and/or Origin polices. Instead the dictionary is converted to a base64 file that is read in via a HTML SRC= command.
Otherwise the "C" file is unchanged.
UnScramble v2 can be found on http://BeNiceGames.com/Tools/UnScramble/UnScramble.html and the README in the UnScramble GitHub repo has been updated accordingly.

take care,
John
